### ISSUE TITLE
ESP32-2432S028R demo project couldn't be runned

### ISSUE THREAD

**Issue by rzeldent** [rzeldent/esp32-smartdisplay#222]
### Discussed in https://github.com/rzeldent/esp32-smartdisplay/discussions/220

<div type='discussions-op-text'>

<sup>Originally posted by **dev-alphagot** November 29, 2024</sup>
## Error Log
```
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
[  5038][I][main.cpp:27] setup(): Board: esp32-2432S028R
[  5044][I][main.cpp:28] setup(): CPU: ESP32-D0WD-V3 rev3, CPU Freq: 240 Mhz, 2 core(s)
[  5052][I][main.cpp:29] setup(): Free heap: 279596 bytes
[  5057][I][main.cpp:30] setup(): Free PSRAM: 0 bytes
[  5062][I][main.cpp:31] setup(): SDK version: v4.4.7-dirty
E (5282) spi: spi_bus_initialize(756): SPI bus already initialized.
ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0x103 (ESP_ERR_INVALID_STATE) at 0x4008883b
  #0  0x4008883b in _esp_error_check_failed_without_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_err.c:37

file: ".pio/libdeps/esp32-2432S028R/esp32_smartdisplay/src/lvgl_touch_xpt2046_spi.c" line 43
func: lvgl_touch_init
expression: spi_bus_initialize(XPT2046_SPI_HOST, &spi_bus_config, XPT2046_SPI_DMA_CHANNEL)
E (5303) lcd_panel.io.spi: esp_lcd_new_panel_io_spi(63): invalid argument
ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x40088850
  #0  0x40088850 in _esp_error_check_failed at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_err.c:42 

file: ".pio/libdeps/esp32-2432S028R/esp32_smartdisplay/src/lvgl_touch_xpt2046_spi.c" line 62
func: lvgl_touch_init
expression: esp_lcd_new_panel_io_spi((esp_lcd_spi_bus_handle_t)XPT2046_SPI_HOST, &io_spi_config, &io_handle)

abort() was called at PC 0x40088853 on core 1


Backtrace: 0x40083add:0x3ffb20a0 0x4008885d:0x3ffb20c0 0x4008e0ad:0x3ffb20e0 0x40088853:0x3ffb2160 0x400feb34:0x3ffb2180 0x400fe887:0x3ffb2220 0x400d17c6:0x3ffb2240 0x40102386:0x3ffb2290
  #0  0x40083add in panic_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/panic.c:408
  #1  0x4008885d in esp_system_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_system.c:137    
  #2  0x4008e0ad in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/newlib/abort.c:46
  #3  0x40088853 in _esp_error_check_failed at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/esp_err.c:43 
  #4  0x400feb34 in lvgl_touch_init at .pio/libdeps/esp32-2432S028R/esp32_smartdisplay/src/lvgl_touch_xpt2046_spi.c:77 (discriminator 1)
  #5  0x400fe887 in smartdisplay_init at .pio/libdeps/esp32-2432S028R/esp32_smartdisplay/src/esp32_smartdisplay.c:210
  #6  0x400d17c6 in setup() at src/main.cpp:33
  #7  0x40102386 in loopTask(void*) at C:/Users/ArisTendou/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:42
```</div>

**Comment by rzeldent** [comment]
Confirmed and reproduced.

**Comment by rzeldent** [comment]
Looked for a solution but problems seems to be that sharing the SPI does not work:

```c
  // Add a device to the SPI bus
    spi_device_interface_config_t device_config = {
        .command_bits = 0,
        .address_bits = 0,
        .dummy_bits = 0,
        .mode = XPT2046_SPI_CONFIG_SPI_MODE,
        .duty_cycle_pos =0,
        .cs_ena_pretrans = 0,
        .cs_ena_posttrans = 0,
        .clock_speed_hz = 0,
        .input_delay_ns = 0,
        .spics_io_num = XPT2046_SPI_CONFIG_CS_GPIO_NUM,
        .flags =  SPI_DEVICE_NO_DUMMY | SPI_DEVICE_HALFDUPLEX,
        .queue_size = XPT2046_SPI_CONFIG_TRANS_QUEUE_DEPTH,
        .pre_cb = NULL,
        .post_cb = NULL,
    };
    spi_device_handle_t io_handle;
    ESP_ERROR_CHECK(spi_bus_add_device(XPT2046_SPI_HOST, &device_config, &io_handle));
```
After initializing the SPI bus (already done by ili9341) the add device fails:

```
file: ".pio/libdeps/esp32-2432S028R/esp32_smartdisplay/src/lvgl_touch_xpt2046_spi.c" line 43
func: lvgl_touch_init
expression: spi_bus_initialize(XPT2046_SPI_HOST, &spi_bus_config, XPT2046_SPI_DMA_CHANNEL)
E (5308) spi_master: spi_master_init_driver(203): SPI Master cannot attach to bus. (Check CONFIG_SPI_FLASH_SHARE_SPI1_BUS)
```

**Comment by rzeldent** [comment]
Just retested the ESP32-2432S028R that I own (with USB-C and USB-micro) and this works using the esp32-2432S028Rv3 definition.
